- termination: reenc
  connections: 200
  samples: 2
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: vegeta
  serverReplicas: 45
  threads: 20
  requestTimeout: 10s
  delay: 10s
  warmup: true

- termination: reenc
  connections: 200
  samples: 5
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: vegeta
  serverReplicas: 45
  threads: 10
  requestTimeout: 10s
  delay: 10s

